name: enfp
description: enfp

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
#  cloud_firestore: ^4.5.0
#  firebase_auth: ^4.4.0
#  firebase_core: ^2.9.0
#  firebase_storage: ^11.1.0
  connectivity: ^3.0.6

  flutter:
    sdk: flutter
  get: ^4.6.5
  google_sign_in: ^6.0.2
  intl: ^0.17.0
  percent_indicator: ^4.2.3
  flutter_shake_animated: ^0.0.5

  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  firebase_auth: ^4.5.0

  image: ^3.1.0
  camera: ^0.9.4+5
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  photo_view: ^0.14.0
  image_picker: ^0.8.7+5

#dependency_overrides:
#  firebase_core_platform_interface: 4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/model/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard/Pretendard-Medium.otf