name: enfp
description: enfp

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  connectivity: ^3.0.6

  flutter:
    sdk: flutter
  get: ^4.6.5
  google_sign_in: ^6.0.2
  intl: ^0.17.0
  percent_indicator: ^4.2.3
  flutter_shake_animated: ^0.0.5

dependency_overrides:
  firebase_core_platform_interface: 4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/image/

  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/font/Pretendard/Pretendard-Medium.otf